version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates

  backend:
    build: ./backend/
    env_file: .env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "./bin/migrate up && ./bin/api/api"]
    develop:
      watch:
        - path: ./backend
          action: rebuild

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=todo_user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build: ./frontend/
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
