version: '3'
services:
  backend:
    build: ./backend/
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "./bin/migrate up && ./bin/api/api"]

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=todo_user
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todo_user -d todo_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
