basePath: /v1
definitions:
  err.Error:
    properties:
      error:
        type: string
    type: object
  err.Errors:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  task.DTO:
    properties:
      completed_date:
        type: string
      created_date:
        type: string
      deleted_date:
        type: string
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  task.Form:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Pawel Gryc
  description: This is a training RESTful API for basic todo app
  title: todo-backend api
  version: "1.0"
paths:
  /../livez:
    get:
      description: Read health
      responses:
        "200":
          description: OK
      summary: Read health
      tags:
      - health
  /items:
    get:
      consumes:
      - application/json
      description: List items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/task.DTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: List items
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Create item
      parameters:
      - description: Item form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.Form'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Create item
      tags:
      - item
  /items/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Delete item
      tags:
      - items
    get:
      consumes:
      - application/json
      description: Read item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Read item
      tags:
      - items
    put:
      consumes:
      - application/json
      description: Delete item
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: string
      - description: Item form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.Form'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Delete item
      tags:
      - items
swagger: "2.0"
